-- Run this in your Supabase SQL editor (https://supabase.com/dashboard/project/qukziojymwlvmrzapgyo/sql)

-- Step 1: Create the table
create table if not exists public.literary_bible (
  id         bigserial primary key,
  book       text        not null,
  chapter    integer     not null,
  verse      integer     not null,
  device     text        not null,
  words      text,
  sources    text,
  urls       text,
  created_at timestamptz default now()
);

create index if not exists idx_lb_book   on public.literary_bible (book);
create index if not exists idx_lb_device on public.literary_bible (device);
create index if not exists idx_lb_ref    on public.literary_bible (book, chapter, verse);

alter table public.literary_bible enable row level security;

create policy "Public read"
  on public.literary_bible for select using (true);

-- Step 2: Insert all 217 rows from your Google Sheet
insert into public.literary_bible (book, chapter, verse, device, words, sources, urls) values
  ('Genesis', 1, 1, 'merism', 'אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ', 'Everett Fox;Harry Orlinsky', 'https://www.sefaria.org/Genesis.1.1?lang=bi&aliyot=0;https://archive.org/details/notesonnewtransl00orli'),
  ('Genesis', 1, 14, 'hendiadys', 'לְאֹתֹת֙ וּלְמ֣וֹעֲדִ֔ים', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli'),
  ('Genesis', 2, 9, 'merism', 'ט֥וֹב וָרָֽע', 'Everett Fox;Harry Orlinsky', 'https://www.sefaria.org/Genesis.2.9?lang=bi&aliyot=0;https://archive.org/details/notesonnewtransl00orli'),
  ('Genesis', 3, 16, 'hendiadys', 'עִצְּבוֹנֵ֣ךְ וְהֵֽרֹנֵ֔ךְ', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 4, 1, 'wordplay', 'קָנִ֥יתִי', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 4, 4, 'waw-explicativum', 'וּמֵֽחֶלְבֵהֶ֑ן', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 4, 12, 'hendiadys', 'נָ֥ע וָנָ֖ד', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 6, 13, 'wordplay', 'מַשְׁחִיתָ֖ם', 'Benno Jacob', 'https://www.amazon.com/Genesis-First-Book-Bible-Augmented/dp/0881259608'),
  ('Genesis', 7, 11, 'wordplay', 'תְּה֣וֹם', 'Rashi', 'https://www.sefaria.org/Genesis.7.11?lang=bi&with=Rashi&lang2=en'),
  ('Genesis', 11, 7, 'wordplay', 'הָ֚בָה', 'Rashi', 'https://www.sefaria.org/Genesis.11.7?lang=en&with=Rashi&lang2=en'),
  ('Genesis', 12, 1, 'hendiadys', 'מֵאַרְצְךָ֥ וּמִמּֽוֹלַדְתְּךָ֖', 'Harry Orlinsky; E.A. Speiser', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up;https://archive.org/details/genesis00spei/page/86/mode/2up'),
  ('Genesis', 12, 13, 'waw-explicativum', 'וְחָיְתָ֥ה נַפְשִׁ֖י בִּגְלָלֵֽךְ', 'Reggio', 'https://www.sefaria.org/Genesis.12.13?lang=en&with=Reggio&lang2=en'),
  ('Genesis', 13, 13, 'hendiadys', 'רָעִ֖ים וְחַטָּאִ֑ים', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 15, 16, 'synecdoche', 'הָאֱמֹרִ֖י', 'Reggio', 'https://www.sefaria.org/Genesis.15.16?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=en&with=Reggio&lang2=en'),
  ('Genesis', 17, 1, 'synecdoche', 'שַׁדַּ֔י', 'Nahum Sarna', 'https://www.amazon.com/JPS-Torah-Commentary-Exodus/dp/0827603274'),
  ('Genesis', 17, 10, 'synecdoche', 'כׇּל־זָכָֽר', 'Reggio', 'https://www.sefaria.org/Genesis.17.10?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=en&with=Reggio&lang2=en'),
  ('Genesis', 18, 26, 'synecdoche', 'סְדֹ֛ם', 'Rashi', 'https://www.sefaria.org/Genesis.18.26?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=en&with=Rashi&lang2=en'),
  ('Genesis', 19, 24, 'hendiadys', 'גׇּפְרִ֣ית וָאֵ֑שׁ', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 20, 4, 'synecdoche', 'הֲג֥וֹי', 'Radak;Seforno', 'https://www.sefaria.org/Genesis.20.4?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Radak&lang2=he;https://www.sefaria.org/Genesis.20.4?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Sforno&lang2=he'),
  ('Genesis', 20, 16, 'sarcasm', 'לְאָחִ֔יךְ', 'Dennis Prager', 'https://www.everand.com/read/404987467/The-Rational-Bible-Genesis#__search-menu_90728'),
  ('Genesis', 21, 23, 'wordplay', 'וּלְנִינִ֖י וּלְנֶכְדִּ֑י', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 22, 19, 'synecdoche', 'אַבְרָהָם֙', 'Ibn Ezra;Radak', 'https://www.sefaria.org/Genesis.22.19?lang=he&with=Ibn%20Ezra&lang2=he;https://www.sefaria.org/Genesis.22.19?lang=he&with=Radak&lang2=he'),
  ('Genesis', 23, 4, 'hendiadys', 'גֵּר־וְתוֹשָׁ֥ב', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 23, 7, 'synecdoche', NULL, 'Seforno', 'https://www.sefaria.org/Genesis.23.7?vhe=Tanach_with_Ta%27amei_Hamikra&lang=he&with=Sforno&lang2=he'),
  ('Genesis', 23, 9, 'synecdoche', 'הַמַּכְפֵּלָה֙', 'Reggio', 'https://www.sefaria.org/Genesis.23.9?lang=he&with=Reggio&lang2=en'),
  ('Genesis', 24, 27, 'hendiadys', 'חַסְדּ֛וֹ וַאֲמִתּ֖וֹ', 'Everett Fox;R. Yitzchak Etshalom', 'https://www.sefaria.org/Genesis.24.27?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Translations&lang2=en;https://oupress.org/product/between-lines-bible-genesis/'),
  ('Genesis', 24, 49, 'hendiadys', 'חֶ֧סֶד וֶֽאֱמֶ֛ת', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 26, 30, 'synecdoche', 'מִשְׁתֶּ֔ה', 'R. Elijah Benamozegh', 'https://www.sefaria.org/Genesis.26.30?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Em%20LaMikra&lang2=en'),
  ('Genesis', 30, 25, 'hendiadys', 'מְקוֹמִ֖י וּלְאַרְצִֽי', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 31, 14, 'hendiadys', 'חֵ֥לֶק וְנַחֲלָ֖ה', 'Robert Alter', 'https://www.google.com/books/edition/The_Five_Books_of_Moses_A_Translation_wi/ZcMhkJ8a708C?hl=en&gbpv=1&dq=robert+alter+five+books+of+moses&printsec=frontcover'),
  ('Genesis', 31, 26, 'synecdoche', 'חָֽרֶב', 'Rashi', 'https://www.sefaria.org/Genesis.31.26?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=en&with=Rashi&lang2=he'),
  ('Genesis', 31, 27, 'hendiadys', 'בְּשִׂמְחָ֥ה וּבְשִׁרִ֖ים', 'Robert Alter', 'https://www.google.com/books/edition/The_Five_Books_of_Moses_A_Translation_wi/ZcMhkJ8a708C?hl=en&gbpv=1&dq=robert+alter+five+books+of+moses&printsec=frontcover'),
  ('Genesis', 31, 54, 'synecdoche', 'לָ֑חֶם', 'Robert Alter', 'https://www.google.com/books/edition/The_Five_Books_of_Moses_A_Translation_wi/ZcMhkJ8a708C?hl=en&gbpv=1&dq=robert+alter+five+books+of+moses&printsec=frontcover'),
  ('Genesis', 32, 29, 'waw-explicativum', 'וְעִם־אֲנָשִׁ֖ים', 'Yair Zakovitch', 'https://libgen.li/ads.php?md5=40709D72BD7004EEC4C1CB57374FB008'),
  ('Genesis', 36, 24, 'waw-explicativum', 'וַעֲנָ֑ה', 'ibn Ezra', 'https://www.sefaria.org/Genesis.36.24?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Genesis', 37, 25, 'synecdoche', 'לֶ֒חֶם֒', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 38, 18, 'synecdoche', 'וּפְתִילֶ֔ךָ', 'Rashi', 'https://www.sefaria.org/Genesis.38.18?lang=he&with=Rashi&lang2=he'),
  ('Genesis', 41, 40, 'synecdoche', 'הַכִּסֵּ֖א', 'Rashi', 'https://www.sefaria.org/Genesis.41.40?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Rashi&lang2=en'),
  ('Genesis', 43, 11, 'hapax', 'בׇּטְנִ֖ים', 'BDB', 'https://www.blueletterbible.org/lexicon/h992/tr/wlc/0-1/'),
  ('Genesis', 43, 12, 'hapax', 'מִשְׁגֶּ֖ה', 'Klein', 'https://www.sefaria.org/Genesis.43.12?lang=bi&lookup=%D7%91%D6%BC%D7%87%D7%98%D6%B0%D7%A0%D6%B4%D6%96%D7%99%D7%9D&with=Halakhah&lang2=en'),
  ('Genesis', 44, 4, 'melitza', 'לָ֛מָּה שִׁלַּמְתֶּ֥ם רָעָ֖ה תַּ֥חַת טוֹבָֽה', 'Matthew Miller', 'https://www.sefaria.org/Genesis.44.4?lang=bi&lookup=%D7%9C%D6%B8%D6%9B%D7%9E%D6%BC%D6%B8%D7%94%20%D7%A9%D7%81%D6%B4%D7%9C%D6%BC%D6%B7%D7%9E%D6%B0%D7%AA%D6%BC%D6%B6%D6%A5%D7%9D%20%D7%A8%D6%B8%D7%A2%D6%B8%D6%96%D7%94%20%D7%AA%D6%BC%D6%B7%D6%A5%D7%97%D6%B7%D7%AA%20%D7%98%D7%95%D6%B9%D7%91%D6%B8%D6%BD%D7%94%D7%83&with=Lexicon&lang2=en'),
  ('Genesis', 45, 6, 'hendiadys', 'חָרִ֖ישׁ וְקָצִֽיר', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 45, 18, 'metaphor', 'חֵ֥לֶב הָאָֽרֶץ', 'Rashi', 'https://www.sefaria.org/Genesis.45.18?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=en&with=Rashi&lang2=he'),
  ('Genesis', 47, 19, 'metaphor', 'נָמ֣וּת', 'Chizkuni', 'https://www.sefaria.org/Genesis.47.19?ven=hebrew|Tanach_with_Ta%27amei_Hamikra&lang=bi&with=Chizkuni&lang2=he'),
  ('Genesis', 47, 29, 'hendiadys', 'חֶ֣סֶד וֶאֱמֶ֔ת', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Genesis', 48, 22, 'synecdoche', 'הָֽאֱמֹרִ֔י', 'Shadal', 'https://www.sefaria.org/Genesis.48.22?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Shadal&lang2=en'),
  ('Exodus', 1, 11, 'waw-explicativum', 'אֶת־פִּתֹ֖ם וְאֶת־רַעַמְסֵֽס׃', 'Sotah 11a', 'https://www.sefaria.org/Sotah.11a.19?lang=bi'),
  ('Exodus', 5, 4, 'synecdoche', 'מֹשֶׁ֣ה וְאַהֲרֹ֔ן', 'ibn Ezra', 'https://www.sefaria.org/Exodus.5.4?lang=en&with=Ibn%20Ezra&lang2=en'),
  ('Exodus', 7, 19, 'merism', 'וּבָעֵצִ֖ים וּבָאֲבָנִֽים', 'Nahum Sarna', 'https://www.amazon.com/JPS-Torah-Commentary-Exodus/dp/0827603274'),
  ('Exodus', 11, 5, 'merism', 'מִבְּכ֤וֹר פַּרְעֹה֙ הַיֹּשֵׁ֣ב עַל־כִּסְא֔וֹ עַ֚ד בְּכ֣וֹר הַשִּׁפְחָ֔ה אֲשֶׁ֖ר אַחַ֣ר הָרֵחָ֑יִם', 'Nahum Sarna', 'https://www.amazon.com/JPS-Torah-Commentary-Exodus/dp/0827603274'),
  ('Exodus', 11, 6, 'wordplay', 'צְעָקָ֥ה', 'Nahum Sarna', 'https://www.amazon.com/JPS-Torah-Commentary-Exodus/dp/0827603274'),
  ('Exodus', 12, 3, 'synecdoche', 'כׇּל־עֲדַ֤ת יִשְׂרָאֵל֙', 'JPS 2006', 'https://www.sefaria.org/Exodus.12.4?lang=bi&lookup=%D7%9E%D7%95%D6%B9%D7%A4%D6%B0%D7%AA%D6%B7%D6%96%D7%99&with=Lexicon&lang2=en'),
  ('Exodus', 12, 6, 'synecdoche', 'כֹּ֛ל קְהַ֥ל עֲדַֽת־יִשְׂרָאֵ֖ל', 'Rashi', 'https://www.sefaria.org/Exodus.12.6?lang=bi&with=Commentary&lang2=en'),
  ('Exodus', 12, 9, 'hapax', 'נָ֔א', 'Klein', 'https://www.sefaria.org/Exodus.12.9?lang=bi&lookup=%D7%9E%D6%B0%D7%A8%D6%B9%D7%A8%D6%B4%D6%96%D7%99%D7%9D&with=Commentary&lang2=en'),
  ('Exodus', 12, 30, 'melitza', 'כִּֽי־אֵ֣ין בַּ֔יִת אֲשֶׁ֥ר אֵֽין־שָׁ֖ם מֵֽת', 'Matthew Miller', 'https://www.sefaria.org/Exodus.12.31?lang=bi&lookup=%D7%94%D6%B7%D7%A9%D7%81%D6%BC%D6%B0%D7%91%D6%B4%D6%94%D7%99&with=Lexicon&lang2=en'),
  ('Exodus', 12, 45, 'hendiadys', 'תּוֹשָׁ֥ב וְשָׂכִ֖יר', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Exodus', 15, 8, 'hapax', 'נֶ֣עֶרְמוּ', 'Klein', 'https://www.sefaria.org/Exodus.15.8?lang=bi&with=Klein%20Dictionary&lang2=en'),
  ('Exodus', 15, 16, 'hapax', 'אֵימָ֙תָה֙', 'Klein', 'https://www.sefaria.org/Exodus.15.16?lang=bi&lookup=%D7%90%D6%B5%D7%99%D7%9E%D6%B8%D6%99%D7%AA%D6%B8%D7%94%D6%99&with=Lexicon&lang2=en'),
  ('Exodus', 15, 25, 'hendiadys', 'חֹ֥ק וּמִשְׁפָּ֖ט', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Exodus', 16, 14, 'hapax', 'מְחֻסְפָּ֔ס', 'Klein (adj. scaly, scale-like (a hapax legomenon in the Bible, occurring Ex. 16:14).  [Part. of חֻסְפַּס (= was scaly, was scale-like). See חספס.])', 'https://www.sefaria.org/Exodus.16.14?lang=bi&aliyot=0&p2=Klein_Dictionary%2C_%D7%9E%D6%B0%D7%97%D6%B0%D7%A1%D6%B0%D7%A4%D6%B8%D6%BC%D7%A1.1&lang2=bi&w2=all&lang3=en'),
  ('Exodus', 22, 28, 'hendiadys', 'מְלֵאָתְךָ֥ וְדִמְעֲךָ֖', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Exodus', 23, 25, 'synecdoche', 'לַחְמְךָ֖', 'Onkelos', 'https://www.sefaria.org/Exodus.23.25?lang=bi&with=Onkelos%20Exodus&lang2=he'),
  ('Exodus', 25, 31, 'hendiadys', 'יְרֵכָ֣הּ וְקָנָ֔הּ', 'Everett Fox', 'https://www.sefaria.org/Exodus.25.31?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=en&with=all&lang2=en'),
  ('Exodus', 26, 12, 'hapax', 'וְסֶ֙רַח֙', 'BDB', 'https://www.sefaria.org/Exodus.26.12?lang=bi&lookup=%D7%A7%D6%B7%D7%A8%D6%B0%D7%A1%D6%B5%D6%A3%D7%99&with=Lexicon&lang2=en'),
  ('Exodus', 32, 25, 'hapax', 'לְשִׁמְצָ֖ה', 'BDB', 'https://www.sefaria.org/Exodus.32.25?lang=bi&lookup=%D7%9C%D6%B0%D7%A9%D7%81%D6%B4%D7%9E%D6%B0%D7%A6%D6%B8%D6%96%D7%94&with=Lexicon&lang2=en'),
  ('Exodus', 35, 11, 'synecdoche', 'הַמִּשְׁכָּ֔ן', 'Rashi', 'https://www.sefaria.org/Exodus.35.11?lang=he&with=Rashi&lang2=he'),
  ('Exodus', 37, 1, 'synecdoche', 'בְּצַלְאֵ֛ל', 'Rashi', 'https://www.sefaria.org/Exodus.37.1?lang=he&with=Rashi&lang2=he'),
  ('Exodus', 40, 19, 'synecdoche', 'הָאֹ֙הֶל֙', 'Rashi', 'https://www.sefaria.org/Exodus.40.19?lang=he&with=Rashi&lang2=he'),
  ('Exodus', 40, 22, 'metaphor', 'יֶ֥רֶךְ', 'Rashi', 'https://www.sefaria.org/Exodus.40.22?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Rashi&lang2=en'),
  ('Leviticus', 1, 16, 'hapax', 'מֻרְאָת֖וֹ', 'Bible Hub', 'https://biblehub.com/hebrew/4760.htm'),
  ('Leviticus', 2, 6, 'hapax', 'פָּת֤וֹת', 'BDB', 'https://www.sefaria.org/Leviticus.2.6?lang=bi&lookup=%D7%94%D6%B7%D6%BD%D7%9E%D6%BC%D6%B7%D7%97%D6%B2%D7%91%D6%B7%D6%96%D7%AA&with=David%20Zvi%20Hoffmann&lang2=en'),
  ('Leviticus', 3, 11, 'synecdoche', 'לֶ֥חֶם', 'Rashi; Reggio', 'https://www.sefaria.org/Leviticus.3.11?lang=he&with=Rashi&lang2=he;https://www.sefaria.org/Leviticus.3.11?lang=bi&with=Reggio&lang2=en'),
  ('Leviticus', 4, 7, 'synecdoche', 'קַ֠רְנ֠וֹת מִזְבַּ֨ח', 'Everett Fox', 'https://www.sefaria.org/Leviticus.4.7?ven=The_Five_Books_of_Moses,_by_Everett_Fox._New_York,_Schocken_Books,_1995&lang=bi&with=Rashi&lang2=en'),
  ('Leviticus', 4, 13, 'synecdoche', 'עֲדַ֤ת', 'Benamozegh', 'https://www.sefaria.org/Leviticus.4.13?lang=bi&with=Em%20LaMikra&lang2=he'),
  ('Leviticus', 6, 14, 'hapax', 'תֻּפִינֵי֙', 'BDB', 'https://www.sefaria.org/Leviticus.6.14?lang=bi&lookup=%D7%AA%D6%BC%D6%BB%D7%A4%D6%B4%D7%99%D7%A0%D6%B5%D7%99%D6%99&with=Lexicon&lang2=en'),
  ('Leviticus', 13, 55, 'hapax', 'פְּחֶ֣תֶת', 'Klein', 'https://www.sefaria.org/Leviticus.13.54?lang=bi&lookup=%D7%A4%D6%BC%D6%B0%D7%97%D6%B6%D6%A3%D7%AA%D6%B6%D7%AA&with=Lexicon&lang2=en'),
  ('Leviticus', 14, 37, 'hapax', 'שְׁקַֽעֲרוּרֹת֙', 'https://www.sefaria.org/Leviticus.14.37?lang=bi&lookup=%D7%A9%D7%81%D6%B0%D7%A7%D6%B7%D6%BD%D7%A2%D6%B2%D7%A8%D7%95%D6%BC%D7%A8%D6%B9%D7%AA%D6%99&with=Talmud&lang2=en', 'BDB'),
  ('Leviticus', 15, 11, 'synecdoche', 'וְיָדָ֖יו לֹא־שָׁטַ֣ף בַּמָּ֑יִם', 'Rashi', 'https://www.sefaria.org/Leviticus.15.11?lang=he&with=Rashi&lang2=en'),
  ('Leviticus', 17, 8, 'merism', 'עֹלָ֖ה אוֹ־זָֽבַח', 'Everett Fox', 'https://www.sefaria.org/Leviticus.17.8?lang=en&with=all&lang2=en'),
  ('Leviticus', 18, 6, 'euphemism', 'עֶרְוָ֑ה', 'Everett Fox', 'https://www.sefaria.org/Leviticus.18.6?lang=bi&with=all&lang2=en'),
  ('Leviticus', 18, 7, 'waw-explicativum', 'וְעֶרְוַ֥ת אִמְּךָ֖', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/216/mode/2up'),
  ('Leviticus', 21, 17, 'synecdoche', 'לֶ֥חֶם', 'Rashi', 'https://www.sefaria.org/Leviticus.21.17?lang=en&with=Rashi&lang2=en'),
  ('Leviticus', 21, 21, 'synecdoche', 'לֶ֣חֶם', 'Rashi', 'https://www.sefaria.org/Leviticus.21.21?lang=en&with=Rashi&lang2=en'),
  ('Leviticus', 25, 10, 'synecdoche', 'יוֹבֵ֥ל', 'Everett Fox', 'https://www.sefaria.org/Leviticus.25.10?lang=en&with=all&lang2=en'),
  ('Leviticus', 25, 35, 'hendiadys', 'גֵּ֧ר וְתוֹשָׁ֛ב', 'Baruch Levine, JPS Bible, Leviticus Introduction, xviii', 'https://archive.org/details/leviticustraditi0000levi'),
  ('Leviticus', 25, 47, 'hendiadys', 'גֵּ֤ר וְתוֹשָׁב֙', 'Baruch Levine;Rashi', 'https://archive.org/details/leviticustraditi0000levi;https://www.sefaria.org/Leviticus.25.47?lang=en&with=Rashi&lang2=en'),
  ('Numbers', 3, 7, 'waw-explicativum', 'וְשָׁמְר֣וּ אֶת־מִשְׁמַרְתּ֗וֹ', 'Rashi', 'https://www.sefaria.org/Numbers.3.6?lang=bi&with=Rashi&lang2=he'),
  ('Numbers', 4, 9, 'synecdoche', 'נֵ֣רֹתֶ֔יהָ', 'Rashi', 'https://www.sefaria.org/Numbers.4.9?lang=en&with=Rashi&lang2=en'),
  ('Numbers', 5, 21, 'euphemism', 'יְרֵכֵךְ֙', 'Everett Fox', 'https://www.sefaria.org/Numbers.5.21?lang=bi&aliyot=0'),
  ('Numbers', 10, 30, 'hendiadys', 'אֶל־אַרְצִ֛י וְאֶל־מוֹלַדְתִּ֖', 'Harry Orlinsky', 'https://archive.org/details/notesonnewtransl00orli/page/n5/mode/2up'),
  ('Numbers', 15, 38, 'synecdoche', 'צִיצִ֛ת', 'Rashi', 'https://www.sefaria.org/Numbers.15.38?lang=en&with=Rashi&lang2=he'),
  ('Numbers', 21, 21, 'synecdoche', 'יִשְׂרָאֵל֙', 'Rashi', 'https://www.sefaria.org/Numbers.21.21?lang=he&with=Rashi&lang2=en'),
  ('Numbers', 24, 17, 'synecdoche', 'בְּנֵי־שֵֽׁת', 'Rashi', 'https://www.sefaria.org/Numbers.24.17?lang=en&with=Rashi&lang2=en'),
  ('Deuteronomy', 16, 6, 'synecdoche', 'תִּזְבַּ֥ח', 'Tur', 'https://www.sefaria.org/Exodus.12.6?lang=bi&with=Commentary&lang2=en'),
  ('Deuteronomy', 17, 17, 'waw-explicativum', 'וְלֹ֥א יָס֖וּר לְבָב֑וֹ', 'Sanhedrin 21a', 'https://www.sefaria.org/Sanhedrin.21a.8?lang=bi&with=Rashi&lang2=en'),
  ('Ezekiel', 45, 15, 'hapax', 'מִמַּשְׁקֵ֣ה', 'Rashi', 'https://www.sefaria.org/Rashi_on_Ezekiel.45.15.3'),
  ('Joel', 1, 2, 'synecdoche', 'בִּֽימֵיכֶ֔ם', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Joe&chapter=1#2'),
  ('Joel', 1, 5, 'synecdoche', 'מִפִּיכֶֽם', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Joe&chapter=1&verse=5'),
  ('Jonah', 1, 2, 'synecdoche', 'עָלֶ֑יהָ', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Jon&chapter=1&verse=2'),
  ('Micah', 2, 9, 'synecdoche', 'נְשֵׁ֤י', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Mic&chapter=2&verse=9'),
  ('Nahum', 2, 3, 'synecdoche', 'וּזְמֹרֵיהֶ֖ם', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Nah&chapter=2#2'),
  ('Psalms', 50, 20, 'hendiadys', 'תֵּ֭שֵׁב בְּאָחִ֣יךָ תְדַבֵּ֑ר', NULL, 'Mitchel Dahood'),
  ('Psalms', 78, 9, 'synecdoche', 'אֶפְרַ֗יִם', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Psa&chapter=78&verse=9'),
  ('Psalms', 99, 5, 'synecdoche', 'לַהֲדֹ֥ם רַגְלָ֗יו', 'Sarna', 'https://www.google.com/books/edition/Exploring_Exodus/CMN7EUB_gMEC?hl=en&gbpv=1&bsq=synecdoche'),
  ('Psalms', 131, 1, 'merism', 'לֹא־גָבַ֣הּ לִ֭בִּי וְלֹא־רָמ֣וּ עֵינַ֑י', 'Adele Berlin', 'https://jps.org/books/jps-bible-commentary-psalms-120-150/'),
  ('Psalms', 132, 7, 'synecdoche', 'לַהֲדֹ֥ם רַגְלָֽיו', 'Sarna', 'https://www.google.com/books/edition/Exploring_Exodus/CMN7EUB_gMEC?hl=en&gbpv=1&bsq=synecdoche'),
  ('Proverbs', 1, 15, 'synecdoche', 'רַ֝גְלְךָ֗', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Pro&chapter=1&verse=15'),
  ('Proverbs', 10, 27, 'synecdoche', 'וּשְׁנ֖וֹת', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Pro&chapter=10#27'),
  ('Proverbs', 11, 29, 'synecdoche', 'בֵּ֭יתוֹ', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Pro&chapter=11&verse=29'),
  ('Proverbs', 14, 1, 'synecdoche', 'בֵיתָ֑הּ', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Pro&chapter=14#1'),
  ('Proverbs', 15, 31, 'synecdoche', 'אֹ֗זֶן', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Pro&chapter=15&verse=31'),
  ('Job', 13, 1, 'melitza', 'הֶן־כֹּ֭ל רָאֲתָ֣ה עֵינִ֑י', 'Matthew Miller', 'https://www.sefaria.org/Job.13.1?lang=bi&with=all&lang2=en'),
  ('Job', 13, 4, 'melitza', 'רֹפְאֵ֖י אֱלִ֣ל', 'Matthew Miller', 'https://www.sefaria.org/Job.13.4?lang=bi&with=all&lang2=en'),
  ('Job', 13, 12, 'melitza', 'מִשְׁלֵי־אֵ֑פֶר', 'Matthew Miller', 'https://www.sefaria.org/Job.13.12?lang=bi&with=all&lang2=en'),
  ('Job', 13, 26, 'melitza', 'עֲוֺנ֥וֹת נְעוּרָֽי', 'Matthew Miller', 'https://www.sefaria.org/Job.13.26?lang=bi&with=all&lang2=en'),
  ('Job', 15, 5, 'melitza', 'לְשׁ֣וֹן עֲרוּמִֽים', 'Matthew Miller', 'https://www.sefaria.org/Job.15.5?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 15, 6, 'melitza', 'יַרְשִׁיעֲךָ֣ פִ֣יךָ וְלֹא־אָ֑נִי', 'Matthew Miller', 'https://www.sefaria.org/Job.15.6?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 15, 12, 'hapax', 'יִּרְזְמ֥וּן', 'Bible Hub;Ibn Ezra', 'https://biblehub.com/hebrew/7335.htm;https://www.sefaria.org/Job.15.12?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 15, 24, 'hapax', 'כִּידֽוֹר', 'Bible Hub; Rashi', 'https://biblehub.com/hebrew/3593.htm;https://www.sefaria.org/Job.15.24?lang=bi&with=Rashi&lang2=en'),
  ('Job', 15, 27, 'hapax', 'פִּימָ֣ה', 'Bible Hub', 'https://biblehub.com/hebrew/6371.htm'),
  ('Job', 15, 29, 'hapax', 'מִנְלָֽם', 'Bible Hub', 'https://biblehub.com/hebrew/4512.htm'),
  ('Job', 16, 2, 'melitza', 'שָׁמַ֣עְתִּי כְאֵ֣לֶּה רַבּ֑וֹת', 'Matthew Miller', 'https://www.sefaria.org/Job.16.2?lang=bi&with=Rashi&lang2=en'),
  ('Job', 16, 15, 'hapax', 'גִלְדִּ֑י', 'Bible Hub', 'https://biblehub.com/hebrew/1539.htm'),
  ('Job', 17, 1, 'hapax', 'נִזְעָ֗כוּ', 'ibn Ezra', 'https://www.sefaria.org/Job.17.1?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 17, 2, 'hapax', 'הֲ֭תֻלִים', 'Bible Hub', 'https://biblehub.com/hebrew/2049.htm'),
  ('Job', 18, 2, 'hapax', 'קִנְצֵ֣י', 'ibn Ezra', 'https://www.sefaria.org/Job.18.2?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 18, 2, 'melitza', 'תָּ֝בִ֗ינוּ וְאַחַ֥ר נְדַבֵּֽר', 'Matthew Miller', 'https://www.sefaria.org/Job.18.2?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 18, 6, 'synecdoche', 'בְּאׇהֳל֑וֹ', 'Sanhedrin 22a', 'https://www.sefaria.org/Sanhedrin.22a.19?lang=bi&with=all&lang2=en'),
  ('Job', 18, 10, 'hapax', 'וּ֝מַלְכֻּדְתּ֗וֹ', 'AlhaTorah', 'https://mg.alhatorah.org/Concordance/4434'),
  ('Job', 18, 14, 'synecdoche', 'מֵ֭אׇהֳלוֹ', 'Rashi', 'https://www.sefaria.org/Job.18.14?lang=bi&with=Rashi&lang2=en'),
  ('Job', 19, 4, 'melitza', 'אִ֝תִּ֗י תָּלִ֥ין מְשׁוּגָתִֽי', 'Matthew Miller', 'https://www.sefaria.org/Job.19.4?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 19, 4, 'hapax', 'מְשׁוּגָתִֽי', 'Bible Hub', 'https://biblehub.com/hebrew/4879.htm'),
  ('Job', 19, 22, 'melitza', 'לָ֭מָּה תִּרְדְּפֻ֣נִי כְמוֹ־אֵ֑ל', 'Matthew Miller', 'https://www.sefaria.org/Job.19.22?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 21, 2, 'melitza', 'שִׁמְע֣וּ שָׁ֭מוֹעַ מִלָּתִ֑י', 'Matthew Miller', 'https://www.sefaria.org/Job.21.2?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 21, 4, 'melitza', 'וְאִם־מַ֝דּ֗וּעַ לֹֽא־תִקְצַ֥ר רוּחִֽי', NULL, 'https://www.sefaria.org/Job.21.4?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 21, 11, 'simile', 'יְשַׁלְּח֣וּ כַ֭צֹּאן עֲוִילֵיהֶ֑ם', 'Matthew Miller', 'https://www.sefaria.org/Job.21.11?lang=bi&with=Rashi&lang2=en'),
  ('Job', 21, 18, 'simile', 'כְּתֶ֥בֶן לִפְנֵי־ר֑וּחַ', 'Matthew Miller', 'https://www.sefaria.org/Job.21.18?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 21, 18, 'simile', 'וּ֝כְמֹ֗ץ גְּנָבַ֥תּוּ סוּפָֽה', 'Matthew Miller', 'https://www.sefaria.org/Job.21.18?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 21, 20, 'hapax', 'כִּיד֑וֹ', 'Rashi;ibn Ezra', 'https://www.sefaria.org/Job.21.20?lang=bi&with=Rashi&lang2=en;https://www.sefaria.org/Job.21.20?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 21, 23, 'hapax', 'שַׁלְאֲנַ֥ן', 'Klein', 'https://www.sefaria.org/Job.21.23?lang=bi&lookup=%D7%A9%D7%81%D6%B7%D7%9C%D6%B0%D7%90%D6%B2%D7%A0%D6%B7%D6%A5%D7%9F&with=Rashi&lang2=en'),
  ('Job', 21, 24, 'hapax', 'עֲ֭טִינָיו', 'Bible Hub;Klein', 'https://biblehub.com/hebrew/5845.htm;https://www.sefaria.org/Klein_Dictionary%2C_%D7%A2%D6%B8%D7%98%D6%B4%D7%99%D7%9F_%E1%B4%B5?ven=english|Carta_Jerusalem%3B_1st_edition,_1987&lang=bi'),
  ('Job', 21, 24, 'metaphor', 'עֲ֭טִינָיו מָלְא֣וּ חָלָ֑ב וּמֹ֖חַ עַצְמוֹתָ֣יו יְשֻׁקֶּֽה', 'Matthew Miller', 'https://www.sefaria.org/Job.21.24?lang=bi&lookup=%D7%A2%D6%B2%D6%AD%D7%98%D6%B4%D7%99%D7%A0%D6%B8%D7%99%D7%95&with=Rashi&lang2=en'),
  ('Job', 21, 27, 'melitza', 'הֵ֣ן יָ֭דַעְתִּי מַחְשְׁבֽוֹתֵיכֶ֑ם', 'Matthew Miller', 'https://www.sefaria.org/Job.21.27?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 21, 32, 'hapax', 'גָּדִ֥ישׁ', 'Klein;ibn Ezra', 'https://www.sefaria.org/Job.21.32?lang=bi&lookup=%D7%92%D6%BC%D6%B8%D7%93%D6%B4%D6%A5%D7%99%D7%A9%D7%81&with=Rashi&lang2=en;https://www.sefaria.org/Job.21.32?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 22, 24, 'hapax', 'בָּ֑צֶר', 'Klein', 'https://www.sefaria.org/Job.22.24?lang=bi&lookup=%D7%95%D6%B0%D7%A9%D7%81%D6%B4%D7%99%D7%AA&with=Steinsaltz&lang2=en'),
  ('Job', 24, 5, 'metaphor', 'פְּרָאִ֨ים ׀ בַּ֥מִּדְבָּ֗ר', 'Matthew Miller', 'https://www.sefaria.org/Job.24.5?lang=bi&with=Rashi&lang2=en'),
  ('Job', 24, 19, 'metaphor', 'שְׁא֣וֹל חָטָֽאוּ', 'Steinsaltz', 'https://www.sefaria.org/Job.24.19?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 24, 20, 'synecdoche', 'רֶ֨חֶם', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Job&chapter=24#20'),
  ('Job', 24, 20, 'simile', 'כָּעֵ֣ץ עַוְלָֽה', 'JPS 1985', 'https://www.sefaria.org/Job.24.20?lang=bi&with=Rashi&lang2=en'),
  ('Job', 24, 24, 'simile', 'וְֽהֻמְּכ֗וּ כַּכֹּ֥ל יִקָּפְצ֑וּן', 'JPS 1985', 'https://www.sefaria.org/Job.24.24?lang=bi&with=all&lang2=en'),
  ('Job', 24, 24, 'simile', 'וּכְרֹ֖אשׁ שִׁבֹּ֣לֶת יִמָּֽלוּ', 'JPS 1985', 'https://www.sefaria.org/Job.24.24?lang=bi&with=all&lang2=en'),
  ('Job', 25, 2, 'hapax', 'הַמְשֵׁ֣ל', 'Klein', 'https://www.sefaria.org/Job.25.2?lang=bi&lookup=%D7%94%D6%B7%D7%9E%D6%B0%D7%A9%D7%81%D6%B5%D6%A3%D7%9C&with=Steinsaltz&lang2=en'),
  ('Job', 26, 4, 'sarcasm', 'אֶת־מִ֭י הִגַּ֣דְתָּ מִלִּ֑ין', 'Steinsaltz', 'https://www.sefaria.org/Job.26.4?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 26, 9, 'hapax', 'פַּרְשֵׁ֖ז', 'Klein;ibn Ezra', 'https://www.sefaria.org/Job.26.9?lang=bi&lookup=%D7%A4%D6%BC%D6%B7%D7%A8%D6%B0%D7%A9%D7%81%D6%B5%D6%96%D7%96&with=Steinsaltz&lang2=en;https://www.sefaria.org/Job.26.9?lang=bi&with=Ibn%20Ezra&lang2=en'),
  ('Job', 26, 11, 'hapax', 'יְרוֹפָ֑פוּ', 'BDB', 'https://www.sefaria.org/Job.26.11?lang=bi&lookup=%D7%99%D6%B0%D7%A8%D7%95%D6%B9%D7%A4%D6%B8%D6%91%D7%A4%D7%95%D6%BC&with=Reference&lang2=en'),
  ('Job', 26, 14, 'hapax', 'שֵּׁ֣מֶץ', 'BDB', 'https://www.sefaria.org/Job.26.14?lang=bi&lookup=%D7%A9%D7%81%D6%BC%D6%B5%D6%A3%D7%9E%D6%B6%D7%A5&with=Steinsaltz&lang2=en'),
  ('Job', 28, 16, 'hapax', 'תְ֭סֻלֶּה', 'Klein', 'https://www.sefaria.org/Klein_Dictionary%2C_%D7%A1%D7%9C%D7%94_%E1%B4%B5%E1%B4%B5.1?lang=bi&with=all&lang2=en'),
  ('Job', 28, 17, 'hapax', 'וּזְכוֹכִ֑ית', 'Bible Hub', 'https://biblehub.com/hebrew/2137.htm'),
  ('Job', 28, 18, 'hapax', 'וְ֭גָבִישׁ', 'Bible Hub', 'https://biblehub.com/hebrew/1378.htm'),
  ('Job', 29, 4, 'melitza', 'כַּאֲשֶׁ֣ר הָ֭יִיתִי בִּימֵ֣י חׇרְפִּ֑י', 'Matthew Miller', 'https://www.sefaria.org/Job.29.4?lang=bi&with=Rashi&lang2=en'),
  ('Job', 29, 6, 'hapax', 'הֲלִיכַ֣י', 'BDB', 'https://www.sefaria.org/Job.29.6?lang=bi&lookup=%D7%94%D6%B2%D7%9C%D6%B4%D7%99%D7%9B%D6%B7%D6%A3%D7%99&with=Steinsaltz&lang2=en'),
  ('Job', 29, 10, 'melitza', 'וּ֝לְשׁוֹנָ֗ם לְחִכָּ֥ם דָּבֵֽקָה', NULL, 'https://www.sefaria.org/Job.29.10?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 29, 14, 'simile', 'כִּמְעִ֥יל וְ֝צָנִ֗יף מִשְׁפָּטִֽי', NULL, 'https://www.sefaria.org/Job.29.10?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 30, 4, 'hapax', 'מַלּ֣וּחַ', 'BDB', 'https://www.sefaria.org/Avodah_Zarah.3b.14?lang=bi&lookup=%D7%94%D6%B7%D7%A7%D6%BC%D6%B9%D7%98%D6%B0%D7%A4%D6%B4%D7%99%D7%9D&with=Lexicon&lang2=en'),
  ('Job', 32, 17, 'melitza', 'אֲחַוֶּ֖ה דֵעִ֣י אַף־אָֽנִי', 'Matthew Miller', 'https://www.sefaria.org/Job.32.17?lang=bi&with=Rashi&lang2=en'),
  ('Job', 32, 18, 'melitza', 'כִּ֭י מָלֵ֣תִי מִלִּ֑ים', 'Matthew Miller', 'https://www.sefaria.org/Job.32.18?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 32, 19, 'simile', 'הִנֵּֽה־בִטְנִ֗י כְּיַ֥יִן', 'Matthew Miller', 'https://www.sefaria.org/Job.32.19?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 32, 20, 'melitza', 'אֲדַבְּרָ֥ה וְיִֽרְוַֽח־לִ֑י אֶפְתַּ֖ח שְׂפָתַ֣י וְאֶעֱנֶֽה', 'Matthew Miller', 'https://www.sefaria.org/Job.32.21?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 33, 6, 'hapax', 'קֹרַ֥צְתִּי', 'BDB;Klein', NULL),
  ('Job', 33, 25, 'hapax', 'רֻֽטְפַ֣שׁ', 'BDB;Klein', 'https://www.sefaria.org/Job.33.25?lang=bi&lookup=%D7%A8%D6%BB%D6%BD%D7%98%D6%B0%D7%A4%D6%B7%D6%A3%D7%A9%D7%81&with=Lexicon&lang2=en;https://www.sefaria.org/Job.33.25?lang=bi&lookup=%D7%A8%D6%BB%D6%BD%D7%98%D6%B0%D7%A4%D6%B7%D6%A3%D7%A9%D7%81&with=Lexicon&lang2=en'),
  ('Job', 37, 16, 'hapax', 'מִפְלְשֵׂי', 'Malbim; Klein', 'https://www.sefaria.org/Job.37.16?lang=bi&with=Commentary&lang2=en;https://www.sefaria.org/Job.37.16?lang=bi&with=Reference&lang2=en'),
  ('Job', 37, 16, 'hapax', 'מִ֝פְלְא֗וֹת', 'Klein', 'https://www.sefaria.org/Job.37.16?lang=bi&with=Reference&lang2=en'),
  ('Job', 38, 8, 'metaphor', 'מֵרֶ֥חֶם', 'Steinsaltz', 'https://www.sefaria.org/Job.38.8?lang=bi&with=Steinsaltz&lang2=en'),
  ('Job', 38, 14, 'simile', 'כְּמ֣וֹ לְבֽוּשׁ', 'Matthew Miller', 'https://www.sefaria.org/Job.38.14?lang=bi&with=Rashi&lang2=en'),
  ('Job', 38, 16, 'hapax', 'נִבְכֵי', 'Ben Yehuda', 'https://benyehuda.org/dict/24412/49182'),
  ('Job', 38, 28, 'hapax', 'אֶגְלֵי', 'Bible Hub', 'https://biblehub.com/hebrew/96.htm'),
  ('Job', 38, 36, 'hapax', 'שֶּׂ֣כְוִי', 'BDB', 'https://www.sefaria.org/Job.38.36?lang=bi&p2=BDB%2C_%D7%A9%D6%B0%D7%82%D7%9B%D6%B4%D7%99%D6%B8%D6%BC%D7%94&lang2=bi&p3=BDB%2C_%D7%98%D6%BB%D7%97%D7%95%D6%B9%D7%AA&lang3=bi'),
  ('Job', 39, 5, 'hapax', 'עָ֝ר֗וֹד', 'Klein', 'https://www.sefaria.org/Job.39.5?lang=bi&lookup=%D7%A2%D6%B8%D6%9D%D7%A8%D6%97%D7%95%D6%B9%D7%93&with=Rashi&lang2=en'),
  ('Job', 42, 13, 'hapax', 'שִׁבְעָ֥נָה', 'Klein', 'https://www.sefaria.org/Job.42.13?lang=bi&lookup=%D7%A9%D7%81%D6%B4%D7%91%D6%B0%D7%A2%D6%B8%D6%A5%D7%A0%D6%B8%D7%94&with=Rashi&lang2=en'),
  ('SongofSongs', 7, 2, 'hapax', 'חַמּוּקֵ֣י', 'BDB', 'https://www.sefaria.org/Song_of_Songs.7.2?lang=bi&lookup=%D7%A0%D6%B8%D7%93%D6%B4%D6%91%D7%99%D7%91&with=Steinsaltz&lang2=en'),
  ('SongofSongs', 7, 3, 'hapax', 'הַסַּ֔הַר', 'BDB', 'https://www.sefaria.org/Song_of_Songs.7.3?lang=bi&lookup=%D7%A9%D7%81%D7%87%D7%A8%D6%B0%D7%A8%D6%B5%D7%9A%D6%B0%D6%99&with=Steinsaltz&lang2=en'),
  ('SongofSongs', 7, 3, 'hapax', 'הַמָּ֑זֶג', 'BDB', 'https://www.sefaria.org/Song_of_Songs.7.3?lang=bi&lookup=%D7%A9%D7%81%D7%87%D7%A8%D6%B0%D7%A8%D6%B5%D7%9A%D6%B0%D6%99&with=Steinsaltz&lang2=en'),
  ('SongofSongs', 7, 9, 'hapax', 'בְּסַנְסִנָּ֑יו', 'BDB', 'https://www.sefaria.org/Song_of_Songs.7.9?lang=bi&lookup=%D7%91%D6%BC%D6%B0%D7%A1%D6%B7%D7%A0%D6%B0%D7%A1%D6%B4%D7%A0%D6%BC%D6%B8%D6%91%D7%99%D7%95&with=Steinsaltz&lang2=en'),
  ('SongofSongs', 7, 10, 'hapax', 'דּוֹבֵ֖ב', 'BDB', 'https://www.sefaria.org/Song_of_Songs.7.10?lang=bi&lookup=%D7%93%D6%BC%D7%95%D6%B9%D7%91%D6%B5%D6%96%D7%91&with=Steinsaltz&lang2=en'),
  ('Ruth', 2, 14, 'hapax', 'וַיִּצְבׇּט', 'Rashi', 'https://www.sefaria.org/Ruth.2.14?lang=bi&with=Rashi&lang2=en'),
  ('Lamentations', 1, 3, 'synecdoche', 'יְהוּדָ֤ה', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Lam&chapter=1#3'),
  ('Lamentations', 1, 7, 'hendiadys', 'עׇנְיָהּ֙ וּמְרוּדֶ֔יהָ', 'Delbert Hillers', 'https://archive.org/details/lamentations0000unse/page/8/mode/2up'),
  ('Lamentations', 1, 9, 'synecdoche', 'בְּשׁוּלֶ֗יהָ', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Lam&chapter=1&verse=9'),
  ('Lamentations', 2, 1, 'synecdoche', 'הֲדֹם־רַגְלָ֖יו', 'Sarna', 'https://www.google.com/books/edition/Exploring_Exodus/CMN7EUB_gMEC?hl=en&gbpv=1&bsq=synecdoche'),
  ('Lamentations', 2, 18, 'synecdoche', 'חוֹמַ֣ת', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Lam&chapter=2#18'),
  ('Lamentations', 3, 64, 'synecdoche', 'יְדֵיהֶֽם', 'Net Bible', 'https://classic.net.bible.org/verse.php?book=Lam&chapter=3&verse=64'),
  ('Lamentations', 4, 2, 'hapax', 'הַמְסֻלָּאִ֖ים', 'BDB', 'https://www.sefaria.org/Lamentations.4.2?lang=bi&lookup=%D7%94%D6%B7%D7%9E%D6%B0%D7%A1%D6%BB%D7%9C%D6%BC%D6%B8%D7%90%D6%B4%D6%96%D7%99%D7%9D&with=Steinsaltz&lang2=en'),
  ('Lamentations', 5, 4, 'synecdoche', 'כֶ֣סֶף', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Lam&chapter=5#4'),
  ('Lamentations', 5, 6, 'synecdoche', 'לָֽחֶם', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Lam&chapter=5#6'),
  ('Lamentations', 5, 9, 'synecdoche', 'לַחְמֵ֔נוּ', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Lam&chapter=5#9'),
  ('Lamentations', 5, 18, 'synecdoche', 'שׁוּעָלִ֖ים', 'Net Bible', 'https://classic.net.bible.org/bible.php?book=Lam&chapter=5#18'),
  ('Ecclesiastes', 9, 1, 'hapax', 'וְלָב֣וּר', 'BDB', 'https://www.sefaria.org/Ecclesiastes.9.1?lang=bi&lookup=%D7%95%D6%B0%D7%9C%D6%B8%D7%91%D6%A3%D7%95%D6%BC%D7%A8&with=Lexicon&lang2=en'),
  ('Ecclesiastes', 9, 10, 'melitza', 'כֹּ֠ל אֲשֶׁ֨ר תִּמְצָ֧א יָֽדְךָ֛ לַעֲשׂ֥וֹת בְּכֹחֲךָ֖ עֲשֵׂ֑ה', 'Matthew Miller', 'https://www.sefaria.org/Ecclesiastes.9.10?lang=bi&with=Steinsaltz&lang2=en'),
  ('Ecclesiastes', 9, 11, 'hapax', 'הַמֵּר֜וֹץ', 'BDB', 'https://www.sefaria.org/Ecclesiastes.9.11?lang=bi&p2=BDB%2C_%D7%9E%D6%B5%D7%A8%D7%95%D6%B9%D7%A5%C2%B2.1&lang2=bi&w2=all&lang3=en'),
  ('Ecclesiastes', 12, 5, 'hapax', 'וְחַתְחַתִּ֣ים', 'BDB', 'https://www.sefaria.org/Ecclesiastes.12.5?lang=bi&lookup=%D7%95%D6%B0%D7%97%D6%B7%D7%AA%D6%B0%D7%97%D6%B7%D7%AA%D6%BC%D6%B4%D6%A3%D7%99%D7%9D&with=Steinsaltz&lang2=he'),
  ('Ecclesiastes', 12, 12, 'hapax', 'וְלַ֥הַג', 'BDB', 'https://www.sefaria.org/Ecclesiastes.12.12?lang=bi&lookup=%D7%95%D6%B0%D7%9C%D6%B7%D6%A5%D7%94%D6%B7%D7%92&with=Rashi&lang2=en'),
  ('Esther', 1, 3, 'hendiadys', 'שָׂרָ֖יו וַעֲבָדָ֑יו', 'Hannah Kahana', 'https://www.google.com/books/edition/Esther/wFOUGWO4AeEC?hl=en&gbpv=1&dq=%22in+our+verse+serves+as+equivalent+for+the+two+nouns%22&pg=PA10&printsec=frontcover'),
  ('Esther', 1, 19, 'ambiguity', 'הַטּוֹבָ֥ה', 'Carey A. Moore', 'https://archive.org/details/bwb_W8-ARO-326'),
  ('Esther', 5, 13, 'melitza', 'וְכׇל־זֶ֕ה אֵינֶ֥נּוּ שֹׁוֶ֖ה לִ֑י', 'Matthew Miller', 'https://www.sefaria.org/Esther.5.13?lang=bi&with=Steinsaltz&lang2=en'),
  ('Esther', 7, 4, 'hapax', 'בְּנֵ֥זֶק', 'BDB', 'https://www.sefaria.org/Esther.7.4?lang=bi&lookup=%D7%9C%D6%B0%D7%94%D6%B7%D7%A9%D7%81%D6%B0%D7%9E%D6%B4%D6%96%D7%99%D7%93&with=Commentary&lang2=en'),
  ('Esther', 8, 10, 'hapax', 'הָֽרַמָּכִֽים', 'BDB', 'https://www.sefaria.org/Esther.8.10?lang=bi&lookup=%D7%94%D6%B8%D7%A8%D6%B6%D6%99%D7%9B%D6%B6%D7%A9%D7%81%D6%99&with=Lexicon&lang2=en'),
  ('Esther', 8, 15, 'hapax', 'וְתַכְרִ֥יךְ', 'BDB', 'https://www.sefaria.org/Esther.8.15?lang=bi&lookup=%D7%95%D6%B0%D7%AA%D6%B7%D7%9B%D6%B0%D7%A8%D6%B4%D6%A5%D7%99%D7%9A%D6%B0&with=Lexicon&lang2=en'),
  ('Daniel', 4, 2, 'hapax', 'וְהַרְהֹרִין֙', 'BDB', 'https://www.sefaria.org/Daniel.4.2?lang=bi&lookup=%D7%94%D6%B5%D7%99%D7%9B%D6%B0%D7%9C%D6%B4%D6%BD&with=Lexicon&lang2=en'),
  ('Daniel', 9, 25, 'melitza', 'וְתֵדַ֨ע וְתַשְׂכֵּ֜ל', 'Matthew Miller', 'https://www.sefaria.org/Daniel.9.25?lang=bi&lookup=%D7%95%D6%B0%D7%AA%D6%B5%D7%93%D6%B7%D6%A8%D7%A2%20%D7%95%D6%B0%D7%AA%D6%B7%D7%A9%D7%82%D6%B0%D7%9B%D6%BC%D6%B5%D6%9C%D7%9C&with=Rashi&lang2=en'),
  ('Daniel', 11, 2, 'melitza', 'וְעַתָּ֕ה אֱמֶ֖ת אַגִּ֣יד לָ֑ךְ', 'Matthew Miller', 'https://www.sefaria.org/Daniel.11.2?lang=bi&lookup=%D7%95%D6%BC%D7%9C%D6%B0%D7%9E%D6%B8%D7%A2%D6%96%D7%95%D6%B9%D7%96&with=Lexicon&lang2=en'),
  ('Daniel', 11, 20, 'hapax', 'הֶ֣דֶר', 'BDB', 'https://www.sefaria.org/Daniel.11.20?lang=bi&lookup=%D7%94%D6%B6%D6%A3%D7%93%D6%B6%D7%A8&with=Commentary&lang2=en'),
  ('Daniel', 11, 23, 'hapax', 'הִֽתְחַבְּר֥וּת', 'Klein', 'https://www.sefaria.org/Klein_Dictionary%2C_%D7%94%D6%B4%D7%AA%D6%B0%D7%97%D6%B7%D7%91%D6%B0%D6%BC%D7%A8%D7%95%D6%BC%D7%AA?lang=bi'),
  ('Daniel', 11, 32, 'hapax', 'בַּחֲלַקּ֑וֹת', 'BDB', 'https://www.sefaria.org/Daniel.11.32?lang=bi&lookup=%D7%9E%D6%B0%D7%A9%D7%81%D6%B9%D7%9E%D6%B5%D6%BD%D7%9D&with=Lexicon&lang2=en'),
  ('Daniel', 11, 43, 'hapax', 'בְּמִכְמַנֵּי֙', 'BDB', 'https://www.sefaria.org/Daniel.11.43?lang=bi&lookup=%D7%9C%D6%B4%D7%A4%D6%B0%D7%9C%D6%B5%D7%99%D7%98%D6%B8%D6%BD%D7%94&with=Commentary&lang2=en'),
  ('Ezra', 6, 4, 'hapax', 'וְנִדְבָּ֖ךְ', 'BDB', 'https://www.sefaria.org/Ezra.6.4?lang=bi&lookup=%D7%9E%D6%B0%D7%A1%D6%BD%D7%95%D6%B9%D7%91%D6%B0%D7%9C%D6%B4%D6%91%D7%99%D7%9F&with=Lexicon&lang2=en'),
  ('Ezra', 6, 4, 'hapax', 'חֲדַ֑ת', 'BDB', 'https://www.sefaria.org/Siddur_Ashkenaz%2C_Weekday%2C_Shacharit%2C_Preparatory_Prayers%2C_Torah_Study.3?lang=bi'),
  ('1Chronicles', 12, 23, 'melitza', 'כִּ֚י לְעֶת־י֣וֹם בְּי֔וֹם', 'Matthew Miller', NULL)
on conflict do nothing;
