[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[functions]
  included_files = [
    "node_modules/node-html-parser/**",
    "public/images/Sukkah Posters/**"
  ]
  excluded_environment_variables = [
    "GOOGLE_DRIVE_API_KEY",
    "GOOGLE_DRIVE_SCP_FOLDER_ID"
  ]
